name: Continuous Integration

# This action works with pull requests, pushes, and merged events
on:
  pull_request:
    types: [closed] # This triggers the workflow when a pull request is closed
  push:
    branches:
      - dev

jobs:
  prettier:
    runs-on: ubuntu-latest
    # Add an if condition to check if the pull request was merged
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
